@extends('app')
@section('content')
<div class="form cf">
	<div class="form cf">
		<!--Channel Definition File for Channel: GetQuote Vertical: MOT--><!--Generated by ChannelGenerator on Tuesday, November 21, 2017 at 9:52:41 AM UTC-->                                    
		<div class="hidden none-edit text cf" id="ResultGUID" style="display:none;">
			<div class="text-label">
			</div>
			<div class="text-answer">
				891794ef-1432-4963-b3f8-3b2bb02af533
			</div>
		</div>
	</div>
	<!-- Main Form START-->
	<div name="MainForm" id="MainForm" class="main-form">
		<div name="MainForm-Container" id="MainForm-Container" class="container">
			<div name="MainForm-r1" id="MainForm-r1" class="row">
				<div name="MainForm-r1c1" id="MainForm-r1c1" class="col-md-3 col-xs-12 pull-right">
					<div name="MainForm-selected-product" id="MainForm-selected-product" class="selected-product">
						<div class="text-heading display-none text cf">
							<div class="text-paragraph">
								Your Selected Insurance
							</div>
						</div>
						<div class="img-container field cf" id="Image">
							<div class="field-image">
								<img src="">
							</div>
						</div>
						<!-- first line of product information-->                                                   
						<div class="product-bankname none-edit text cf" id="Generic_output_insurancecompany_nonedit">
							<div class="text-label">
								Insurer:
							</div>
							<div class="text-answer">
								AFP General Insurance Corporation
							</div>
						</div>
						<div class="product-name to-hide none-edit text cf" id="CLO_output_productname_nonedit">
							<div class="text-label">
								Your selected product:
							</div>
							<div class="text-answer">
								AFP General Insurance Corporation
							</div>
						</div>
						<a href="javascript:;" class="btn btn-link display-none more-details">More details</a>
					</div>
				</div>
				<div name="MainForm-r1c2" id="MainForm-r1c2" class="col-md-9 col-xs-12">
					<div name="MainForm-r1c2r1" id="MainForm-r1c2r1" class="row">
						<div name="MainForm-r1c2c1" id="MainForm-r1c2c1" class="col-sm-3 col-xs-12 pull-right text-login">                                                      <a href="javascript:;" class="btn btn-link sign-in">Login to fill in form</a>
						</div>
					</div>
					<div name="MainForm-r1c2r2" id="MainForm-r1c2r2" class="row">
						<input id="FormQuestions_18__ValidationDefinition_0__Name" name="FormQuestions[18].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_18__ValidationDefinition_0__ErrorMessage" name="FormQuestions[18].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter your first name"><input id="FormQuestions_18__ValidationDefinition_1__Name" name="FormQuestions[18].ValidationDefinition[1].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_18__ValidationDefinition_1__ErrorMessage" name="FormQuestions[18].ValidationDefinition[1].ErrorMessage" type="hidden" value="Come on. Enter at least a second character :-)"><input id="FormQuestions_18__ValidationDefinition_1__Data_0_" name="FormQuestions[18].ValidationDefinition[1].Data[0]" type="hidden" value="2"><input id="FormQuestions_18__ValidationDefinition_1__Data_1_" name="FormQuestions[18].ValidationDefinition[1].Data[1]" type="hidden" value="50">                                    
						<div class="col-sm-4 col-xs-6 field cf" id="contact_applicant_firstname">
							<label class="text-label">
							First Name
							<span class="field-question" title="" data-original-title="Please enter your first name as stated in any of your Government issued ID.">?</span>
							</label>
							<div class="form-group field-input">
								<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter your first name&quot;,&quot;Data&quot;:null},{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Come on. Enter at least a second character :-)&quot;,&quot;Data&quot;:[&quot;2&quot;,&quot;50&quot;]}]" id="FormQuestions_18__Answer" name="FormQuestions[18].Answer" placeholder="" type="text" value="Eul" aria-required="true">
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[18].Answer" data-valmsg-replace="true"></span>
						</div>
						<div class="col-sm-4 col-xs-6 field cf" id="contact_applicant_middlename">
							<label class="text-label">
							Middle Name
							<span class="field-question" title="" data-original-title="Please enter your middle name as stated in any of your Government issued ID. If you dont have a middle name just leave the field empty.">?</span>
							</label>
							<div class="form-group field-input">
								<input class="form-control" data-valdef="[]" id="FormQuestions_20__Answer" name="FormQuestions[20].Answer" placeholder="" type="text" value="">
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[20].Answer" data-valmsg-replace="true"></span>
						</div>
						<input id="FormQuestions_22__ValidationDefinition_0__Name" name="FormQuestions[22].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_22__ValidationDefinition_0__ErrorMessage" name="FormQuestions[22].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter your family name"><input id="FormQuestions_22__ValidationDefinition_1__Name" name="FormQuestions[22].ValidationDefinition[1].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_22__ValidationDefinition_1__ErrorMessage" name="FormQuestions[22].ValidationDefinition[1].ErrorMessage" type="hidden" value="Come on. Enter at least a second character :-)"><input id="FormQuestions_22__ValidationDefinition_1__Data_0_" name="FormQuestions[22].ValidationDefinition[1].Data[0]" type="hidden" value="2"><input id="FormQuestions_22__ValidationDefinition_1__Data_1_" name="FormQuestions[22].ValidationDefinition[1].Data[1]" type="hidden" value="50">                                    
						<div class="col-sm-4 col-xs-12 field cf" id="contact_applicant_lastname">
							<label class="text-label">
							Last Name
							<span class="field-question" title="" data-original-title="Please enter your surname as written in any of your Government issued ID.">?</span>
							</label>
							<div class="form-group field-input">
								<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter your family name&quot;,&quot;Data&quot;:null},{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Come on. Enter at least a second character :-)&quot;,&quot;Data&quot;:[&quot;2&quot;,&quot;50&quot;]}]" id="FormQuestions_22__Answer" name="FormQuestions[22].Answer" placeholder="" type="text" value="Araneta" aria-required="true">
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[22].Answer" data-valmsg-replace="true"></span>
						</div>
					</div>
					<div name="MainForm-r1c2r4" id="MainForm-r1c2r4" class="row">
						<input id="FormQuestions_24__ValidationDefinition_0__Name" name="FormQuestions[24].ValidationDefinition[0].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_24__ValidationDefinition_0__ErrorMessage" name="FormQuestions[24].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please select your gender"><input id="FormQuestions_24__ValidationDefinition_0__Data_0_" name="FormQuestions[24].ValidationDefinition[0].Data[0]" type="hidden" value="3"><input id="FormQuestions_24__ValidationDefinition_0__Data_1_" name="FormQuestions[24].ValidationDefinition[0].Data[1]" type="hidden" value="15">                                    
						<div class="col-sm-4 col-xs-6 field cf" id="contact_applicant_gender">
							<label class="text-label">
							Gender
							<span class="field-question" title="" data-original-title="Please select your gender as stated in any of your Government issued ID.">?</span>
							</label>
							<div class="form-group field-input">
								<select class="form-control select" data-valdef="[{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please select your gender&quot;,&quot;Data&quot;:[&quot;3&quot;,&quot;15&quot;]}]" id="FormQuestions_24__Answer" name="FormQuestions[24].Answer" onchange="">
									<option value="-1">Please select</option>
									<option selected="selected" value="true">Male</option>
									<option value="false">Female</option>
								</select>
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[24].Answer" data-valmsg-replace="true"></span>
						</div>
						<input id="FormQuestions_26__ValidationDefinition_0__Name" name="FormQuestions[26].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_26__ValidationDefinition_0__ErrorMessage" name="FormQuestions[26].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please tell us your birthdate to make sure your age range is covered by the bank."><input id="FormQuestions_26__ValidationDefinition_1__Name" name="FormQuestions[26].ValidationDefinition[1].Name" type="hidden" value="[ValidateAge]"><input id="FormQuestions_26__ValidationDefinition_1__ErrorMessage" name="FormQuestions[26].ValidationDefinition[1].ErrorMessage" type="hidden" value="Please check your entered age. You have to be within 18 to 70 years old to legally enter a contract."><input id="FormQuestions_26__ValidationDefinition_1__Data_0_" name="FormQuestions[26].ValidationDefinition[1].Data[0]" type="hidden" value="18"><input id="FormQuestions_26__ValidationDefinition_1__Data_1_" name="FormQuestions[26].ValidationDefinition[1].Data[1]" type="hidden" value="70">                                    
						<div class="col-sm-4 col-xs-6 icon icon-right datepick-icon field cf" id="CC_contact_applicant_birthdate">
							<label class="text-label">
							Your birthdate:
							<span class="field-question" title="" data-original-title="Please enter your birthdate as stated in any of your Government Issued ID .">?</span>
							</label>
							<div class="form-group field-input">
								<input class="form-control hasDatepicker" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;Please tell us your birthdate to make sure your age range is covered by the bank.&quot;,&quot;Data&quot;:null},{&quot;Name&quot;:&quot;[ValidateAge]&quot;,&quot;ErrorMessage&quot;:&quot;Please check your entered age. You have to be within 18 to 70 years old to legally enter a contract.&quot;,&quot;Data&quot;:[&quot;18&quot;,&quot;70&quot;]}]" id="FormQuestions_26__Answer" name="FormQuestions[26].Answer" placeholder="" type="text" value="3/7/1993 1:43:06 AM" aria-required="true">
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[26].Answer" data-valmsg-replace="true"></span>
						</div>
						<input id="FormQuestions_28__ValidationDefinition_0__Name" name="FormQuestions[28].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_28__ValidationDefinition_0__ErrorMessage" name="FormQuestions[28].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter a email address"><input id="FormQuestions_28__ValidationDefinition_1__Name" name="FormQuestions[28].ValidationDefinition[1].Name" type="hidden" value="[Email]"><input id="FormQuestions_28__ValidationDefinition_1__ErrorMessage" name="FormQuestions[28].ValidationDefinition[1].ErrorMessage" type="hidden" value="Your entered email does not appear to be valid. Please check again.">                                    
						<div class="col-sm-4 col-xs-12 icon icon-right email-icon field cf" id="contact_applicant_email">
							<label class="text-label">
							Email (to send you the quotation):
							<span class="field-question" title="" data-original-title="Please provide us with your email address so we can send you the quote. Many insurers/Banks prefer to communicate via email and for insurance you will receive the policy document through email as well.">?</span>
							</label>
							<div class="form-group field-input">
								<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a email address&quot;,&quot;Data&quot;:null},{&quot;Name&quot;:&quot;[Email]&quot;,&quot;ErrorMessage&quot;:&quot;Your entered email does not appear to be valid. Please check again.&quot;,&quot;Data&quot;:null}]" id="FormQuestions_28__Answer" name="FormQuestions[28].Answer" placeholder="" type="text" value="eul.araneta@gmail.com" aria-required="true">
							</div>
							<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[28].Answer" data-valmsg-replace="true"></span>
						</div>
					</div>
					<div name="MainForm-r1c2r5" id="MainForm-r1c2r5" class="row">
						<!-- input fields - block 2 - phone numbers-->                                                   
						<div class="col-lg-12 text cf">
							<div class="text-paragraph">
								Please provide us with a phone number in case we need to discuss your application with you (eComparemo.com will never share your data with any 3rd party). Supplying a home phone number is required for some banks and a plus for others - but we can discuss that later.
							</div>
						</div>
					</div>
					<div name="MainForm-r1c2r6" id="MainForm-r1c2r6" class="row">
						<!--first block-->               
						<div name="MainForm-r1c2r6c1" id="MainForm-r1c2r6c1" class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<div name="MainForm-r1c2r6c1r1" id="MainForm-r1c2r6c1r1" class="row">
								<input id="FormQuestions_33__ValidationDefinition_0__Name" name="FormQuestions[33].ValidationDefinition[0].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_33__ValidationDefinition_0__ErrorMessage" name="FormQuestions[33].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter a valid country code"><input id="FormQuestions_33__ValidationDefinition_0__Data_0_" name="FormQuestions[33].ValidationDefinition[0].Data[0]" type="hidden" value="1"><input id="FormQuestions_33__ValidationDefinition_0__Data_1_" name="FormQuestions[33].ValidationDefinition[0].Data[1]" type="hidden" value="5"><input id="FormQuestions_33__ValidationDefinition_1__Name" name="FormQuestions[33].ValidationDefinition[1].Name" type="hidden" value="[Required]"><input id="FormQuestions_33__ValidationDefinition_1__ErrorMessage" name="FormQuestions[33].ValidationDefinition[1].ErrorMessage" type="hidden" value="The country code is required. The country code of the Philippines is 63">                                    
								<div class="col-lg-3 col-md-4 col-sm-3 col-xs-3 field cf" id="Generic_phone_generic_country_required">
									<label class="text-label">
									Country
									</label>
									<div class="form-group field-input">
										<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a valid country code&quot;,&quot;Data&quot;:[&quot;1&quot;,&quot;5&quot;]},{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;The country code is required. The country code of the Philippines is 63&quot;,&quot;Data&quot;:null}]" id="FormQuestions_33__Answer" name="FormQuestions[33].Answer" placeholder="" type="text" value="+63" aria-required="true">
									</div>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[33].Answer" data-valmsg-replace="true"></span>
								</div>
								<input id="FormQuestions_35__ValidationDefinition_0__Name" name="FormQuestions[35].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_35__ValidationDefinition_0__ErrorMessage" name="FormQuestions[35].ValidationDefinition[0].ErrorMessage" type="hidden" value="We need your mobile phone number to contact you in case we have any questions related to your quotation"><input id="FormQuestions_35__ValidationDefinition_1__Name" name="FormQuestions[35].ValidationDefinition[1].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_35__ValidationDefinition_1__ErrorMessage" name="FormQuestions[35].ValidationDefinition[1].ErrorMessage" type="hidden" value="Please enter a valid phone number"><input id="FormQuestions_35__ValidationDefinition_1__Data_0_" name="FormQuestions[35].ValidationDefinition[1].Data[0]" type="hidden" value="10"><input id="FormQuestions_35__ValidationDefinition_1__Data_1_" name="FormQuestions[35].ValidationDefinition[1].Data[1]" type="hidden" value="10"><input id="FormQuestions_35__ValidationDefinition_2__Name" name="FormQuestions[35].ValidationDefinition[2].Name" type="hidden" value="[Regex]"><input id="FormQuestions_35__ValidationDefinition_2__ErrorMessage" name="FormQuestions[35].ValidationDefinition[2].ErrorMessage" type="hidden" value="Please enter mobile number start with number 9"><input id="FormQuestions_35__ValidationDefinition_2__Data_0_" name="FormQuestions[35].ValidationDefinition[2].Data[0]" type="hidden" value="^[9][0-9]*$">                                    
								<div class="col-lg-9 col-md-8 col-sm-9 col-xs-9 mobilenumber field cf" id="CC_contact_applicant_mobilenumber">
									<label class="text-label">
									Mobile Number:
									<span class="field-question" title="" data-original-title="Please enter your mobile phone number including the operator code here">?</span>
									</label>
									<div class="form-group field-input">
										<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;We need your mobile phone number to contact you in case we have any questions related to your quotation&quot;,&quot;Data&quot;:null},{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a valid phone number&quot;,&quot;Data&quot;:[&quot;10&quot;,&quot;10&quot;]},{&quot;Name&quot;:&quot;[Regex]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter mobile number start with number 9&quot;,&quot;Data&quot;:[&quot;^[9][0-9]*$&quot;]}]" id="FormQuestions_35__Answer" name="FormQuestions[35].Answer" placeholder="" type="text" value="09795623542" aria-required="true">
									</div>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[35].Answer" data-valmsg-replace="true"></span>
								</div>
								<div class="col-lg-12 block-sub-text text cf">
									<div class="text-paragraph">
										example: +63-9470999999 (for country code +63 and mobile number 9470999999)
									</div>
								</div>
							</div>
						</div>
						<div name="MainForm-r1c2r6c2" id="MainForm-r1c2r6c2" class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<!-- input fields - block 2 - phone numbers-->                  
							<div name="MainForm-r1c2r6c2r1" id="MainForm-r1c2r6c2r1" class="row">
								<input id="FormQuestions_39__ValidationDefinition_0__Name" name="FormQuestions[39].ValidationDefinition[0].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_39__ValidationDefinition_0__ErrorMessage" name="FormQuestions[39].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter a valid country code"><input id="FormQuestions_39__ValidationDefinition_0__Data_0_" name="FormQuestions[39].ValidationDefinition[0].Data[0]" type="hidden" value="1"><input id="FormQuestions_39__ValidationDefinition_0__Data_1_" name="FormQuestions[39].ValidationDefinition[0].Data[1]" type="hidden" value="5">                                    
								<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 field cf" id="Generic_phone_generic_country">
									<label class="text-label">
									Country
									</label>
									<div class="form-group field-input">
										<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a valid country code&quot;,&quot;Data&quot;:[&quot;1&quot;,&quot;5&quot;]}]" id="FormQuestions_39__Answer" name="FormQuestions[39].Answer" placeholder="" type="text" value="+63">
									</div>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[39].Answer" data-valmsg-replace="true"></span>
								</div>
								<input id="FormQuestions_41__ValidationDefinition_0__Name" name="FormQuestions[41].ValidationDefinition[0].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_41__ValidationDefinition_0__ErrorMessage" name="FormQuestions[41].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter a valid area code"><input id="FormQuestions_41__ValidationDefinition_0__Data_0_" name="FormQuestions[41].ValidationDefinition[0].Data[0]" type="hidden" value="2"><input id="FormQuestions_41__ValidationDefinition_0__Data_1_" name="FormQuestions[41].ValidationDefinition[0].Data[1]" type="hidden" value="4">                                    
								<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 field cf" id="Generic_phone_generic_area_code">
									<label class="text-label">
									Area
									</label>
									<div class="form-group field-input">
										<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a valid area code&quot;,&quot;Data&quot;:[&quot;2&quot;,&quot;4&quot;]}]" id="FormQuestions_41__Answer" name="FormQuestions[41].Answer" placeholder="" type="text" value="">
									</div>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[41].Answer" data-valmsg-replace="true"></span>
								</div>
								<input id="FormQuestions_43__ValidationDefinition_0__Name" name="FormQuestions[43].ValidationDefinition[0].Name" type="hidden" value="[StringLenght]"><input id="FormQuestions_43__ValidationDefinition_0__ErrorMessage" name="FormQuestions[43].ValidationDefinition[0].ErrorMessage" type="hidden" value="Please enter a valid number"><input id="FormQuestions_43__ValidationDefinition_0__Data_0_" name="FormQuestions[43].ValidationDefinition[0].Data[0]" type="hidden" value="5"><input id="FormQuestions_43__ValidationDefinition_0__Data_1_" name="FormQuestions[43].ValidationDefinition[0].Data[1]" type="hidden" value="10">                                    
								<div class="col-sm-6 col-xs-6 field cf" id="Generic_phone_home_number">
									<label class="text-label">
									Home number
									</label>
									<div class="form-group field-input">
										<input class="form-control" data-valdef="[{&quot;Name&quot;:&quot;[StringLenght]&quot;,&quot;ErrorMessage&quot;:&quot;Please enter a valid number&quot;,&quot;Data&quot;:[&quot;5&quot;,&quot;10&quot;]}]" id="FormQuestions_43__Answer" name="FormQuestions[43].Answer" placeholder="" type="text" value="">
									</div>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[43].Answer" data-valmsg-replace="true"></span>
								</div>
								<div class="col-lg-12 block-sub-text text cf">
									<div class="text-paragraph">
										example: +63-02-4444444 (for country code +63, area code 02 and home number 4444444)
									</div>
								</div>
							</div>
						</div>
					</div>
					<div name="MainForm-r1c2r8" id="MainForm-r1c2r8" class="row">
						<!-- Customers consent to saving and using his personal data-->               <input id="FormQuestions_47__ValidationDefinition_0__Name" name="FormQuestions[47].ValidationDefinition[0].Name" type="hidden" value="[Required]"><input id="FormQuestions_47__ValidationDefinition_0__ErrorMessage" name="FormQuestions[47].ValidationDefinition[0].ErrorMessage" type="hidden" value="You have to check this box to continue">                                    
						<div class="col-lg-12 field cf" id="Insurance_Consent_Checkbox">
							<label class="text-label">
							Consent for storing personal data:
							</label>
							<div class="checkbox-button">
								<div class="checkbox-container cf">
									<label>
									<span class="checkbox-input">
									<input type="checkbox" name="FormQuestions[47].Answer" value="true" data-valdef="[{&quot;Name&quot;:&quot;[Required]&quot;,&quot;ErrorMessage&quot;:&quot;You have to check this box to continue&quot;,&quot;Data&quot;:null}]" aria-required="true">
									<span class="checkbox-status"></span>
									</span>
									<span class="checkbox-label">I allow eCompareMo to collect, store and process my personal information - including but not limited to my name, address, phone number, email, etc., as supplied for transactions on this website. Transactions may include cookie placement, personalized offers, enrollment in its newsletter and others. The use and processing of my information shall be in accordance with applicable laws and eCompareMo’s <a href="https://www.ecomparemo.com/terms-conditions">Terms and Conditions</a> and <a href="https://www.ecomparemo.com/privacy-policy">Privacy Policy</a>, which I confirm to have read and understood.</span>
									</label>
									<span class="field-validation-valid text-danger" data-valmsg-for="FormQuestions[47].Answer" data-valmsg-replace="true"></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container" id="buttonProgress">
		<div class="buttons-container row">
			<div class="col-md-9 col-xs-12">
				<div class="border-top"></div>
				<button type="submit" class="btn btn-ghost-default cancel" name="submitAction" value="Back">Back</button>
				<button type="submit" class="btn btn-default" name="submitAction" value="Next">Next</button>
			</div>
		</div>
	</div>
</div>
@endsection
@section('scripts')
<script>{{ asset('js/poppper.min.js') }}</script>
@endsection